AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates an S3 bucket for storing built lambda artefacts for devops deployments, which may be accessed
  by other accounts within this AWS Organization

Parameters:
  TargetOrgUnitIds:
    Description: Target organization units for deploying solution
    Type: CommaDelimitedList

  StackSetName:
    Type: String
    Default: tbs-devops-cfnhooks-stackset

  TemplateUrl:
    Description: S3 URL of CF template which defined our SAM solution for lambda hooks
    Type: String

Resources:
  CfnLambdaHookStackset:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStackOnAccountRemoval: false
      Capabilities: [CAPABILITY_IAM, CAPABILITY_NAMED_IAM]
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - Regions:
            - ap-southeast-2
          DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOrgUnitIds
      StackSetName: !Ref StackSetName
      TemplateURL: !Ref TemplateUrl